<?php

namespace App\Modules\Role\Model;

use Illuminate\Database\Eloquent\Model;

class RoleModel extends Model
{


    protected  $table ="sys_role";

    protected $guarded =[];

    protected $primaryKey = "id";

    public function users(){
        return $this->hasMany("App\Modules\User\Model\UserModel","role_id","id");
    }

    /**
     * @Notes:关联删除。 删除角色后 连上角色对应的用户都删除
     * @Interface boot
     * @author: liwei
     * @Time: 2019/11/12   11:56
     */
    protected static  function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static ::deleting(function ($role){
            $role->users()->delete();
        });
    }
}
